import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter  } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PiggyBanx",
  description: "Generated by create next app",
  icons: {
    icon: "/piggybanx_logo_3.svg",
  },
};

export const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
          <div className="min-h-screen bg-black text-white">
            <Header />
            <main>{children}</main>
            {/* <Sidebar /> */}
          </div>
      </body>
    </html>
  );
}
